# GET http://localhost:9000/api/message/

# POST http://localhost:9000/api/message/
# content-type: application/json

# {
#     "content": "How you doing?",
#     "to": "640ddf249eac9e1c046de956",
#     "from": "640eaeb4b62e1470233bf305"
# }

# GET http://localhost:9000/api/message/userMessages?to=640ddf249eac9e1c046de956&from=640eaeb4b62e1470233bf305
# content-type: application/json